# Generated by Django 4.1.1 on 2022-09-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_name", models.CharField(max_length=50)),
                ("blog_description", models.TextField()),
                ("blog_choice", models.CharField(default="Sports", max_length=20)),
            ],
        ),
    ]
