# Generated by Django 4.1.1 on 2022-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="blog_choice",
            field=models.CharField(
                choices=[("Sports", "Sports")], default="Sports", max_length=20
            ),
        ),
    ]
